export const contractAddress = "0x7cA495B489910fd468fEd2444E8F1C9F034DC430"; //GoldChain Testnet
export const contractAbi = [
    { inputs: [{ internalType: "address payable", name: "fundReceiver", type: "address" }], payable: false, stateMutability: "nonpayable", type: "constructor" },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "address", name: "owner", type: "address" },
            { indexed: true, internalType: "address", name: "spender", type: "address" },
            { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
        ],
        name: "Approval",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
            { indexed: true, internalType: "address", name: "newOwner", type: "address" },
        ],
        name: "OwnershipTransferred",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "address", name: "from", type: "address" },
            { indexed: true, internalType: "address", name: "to", type: "address" },
            { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
        ],
        name: "Transfer",
        type: "event",
    },
    { payable: true, stateMutability: "payable", type: "fallback" },
    {
        constant: true,
        inputs: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "address", name: "spender", type: "address" },
        ],
        name: "allowance",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "approve",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ internalType: "address", name: "account", type: "address" }],
        name: "balanceOf",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: false,
        inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
        name: "burn",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    { constant: false, inputs: [], name: "clearFund", outputs: [], payable: false, stateMutability: "nonpayable", type: "function" },
    { constant: true, inputs: [], name: "decimals", outputs: [{ internalType: "uint8", name: "", type: "uint8" }], payable: false, stateMutability: "view", type: "function" },
    {
        constant: false,
        inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "subtractedValue", type: "uint256" },
        ],
        name: "decreaseAllowance",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [{ internalType: "address", name: "refer", type: "address" }],
        name: "getAirdrop",
        outputs: [{ internalType: "bool", name: "success", type: "bool" }],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    { constant: true, inputs: [], name: "getOwner", outputs: [{ internalType: "address", name: "", type: "address" }], payable: false, stateMutability: "view", type: "function" },
    {
        constant: false,
        inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "addedValue", type: "uint256" },
        ],
        name: "increaseAllowance",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    { constant: true, inputs: [], name: "name", outputs: [{ internalType: "string", name: "", type: "string" }], payable: false, stateMutability: "view", type: "function" },
    { constant: true, inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], payable: false, stateMutability: "view", type: "function" },
    { constant: false, inputs: [], name: "renounceOwnership", outputs: [], payable: false, stateMutability: "nonpayable", type: "function" },
    {
        constant: false,
        inputs: [{ internalType: "address payable", name: "fundReceiver", type: "address" }],
        name: "setFundReceiver",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { internalType: "uint256", name: "airdropStartBlock", type: "uint256" },
            { internalType: "uint256", name: "airdropEndBlock", type: "uint256" },
            { internalType: "uint256", name: "airdropAmount", type: "uint256" },
            { internalType: "uint256", name: "airdropCap", type: "uint256" },
        ],
        name: "startAirdrop",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { internalType: "uint256", name: "saleStartBlock", type: "uint256" },
            { internalType: "uint256", name: "saleEndBlock", type: "uint256" },
            { internalType: "uint256", name: "saleChunk", type: "uint256" },
            { internalType: "uint256", name: "salePrice", type: "uint256" },
            { internalType: "uint256", name: "saleCap", type: "uint256" },
        ],
        name: "startSale",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    { constant: true, inputs: [], name: "symbol", outputs: [{ internalType: "string", name: "", type: "string" }], payable: false, stateMutability: "view", type: "function" },
    {
        constant: false,
        inputs: [{ internalType: "address", name: "refer", type: "address" }],
        name: "tokenSale",
        outputs: [{ internalType: "bool", name: "success", type: "bool" }],
        payable: true,
        stateMutability: "payable",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "totalSupply",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { internalType: "address", name: "recipient", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "transfer",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { internalType: "address", name: "sender", type: "address" },
            { internalType: "address", name: "recipient", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "transferFrom",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
        name: "transferOwnership",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "viewAirdrop",
        outputs: [
            { internalType: "uint256", name: "airdropStartBlock", type: "uint256" },
            { internalType: "uint256", name: "airdropEndBlock", type: "uint256" },
            { internalType: "uint256", name: "airdropCap", type: "uint256" },
            { internalType: "uint256", name: "airdropTotal", type: "uint256" },
            { internalType: "uint256", name: "airdropAmount", type: "uint256" },
        ],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "viewFundReceiver",
        outputs: [{ internalType: "address", name: "fundReceiver", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "viewSale",
        outputs: [
            { internalType: "uint256", name: "saleStartBlock", type: "uint256" },
            { internalType: "uint256", name: "saleEndBlock", type: "uint256" },
            { internalType: "uint256", name: "saleCap", type: "uint256" },
            { internalType: "uint256", name: "saleTotal", type: "uint256" },
            { internalType: "uint256", name: "saleChunk", type: "uint256" },
            { internalType: "uint256", name: "salePrice", type: "uint256" },
        ],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
];
